[package]
name = "ballot"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cita-vm = { git = "https://github.com/citahub/cita-vm" }
ethereum-types = "0.4"
hex = "0.4.0"
